### ISSUE TITLE
FetchError: Redirect location header missing when creating order

### ISSUE THREAD

**Issue by marcoalkema** [wavesplatform/waves-api#29]
Not sure if this belongs here, so please remove when inappropriate.

First thank you very much for writing this lib and especially for doing it in Typescript. It makes it more clear faster!

Whenever I try to create an order, I get the following error:
`WavesRequestError: Server request to 'https://nodes.wavesnodes.com/matcher/orderbook' has failed:`

`FetchError: redirect location header missing at: https://nodes.wavesnodes.com/matcher/orderbook`

My code:
```
  const orderStream =
        Rx.Observable
        .fromPromise(Waves.API.Matcher.v1.getMatcherKey())
        .flatMap(matcherKey =>
                 Rx.Observable
                 .fromPromise(Waves.API.Matcher.v1.createOrder({
                   publicKey: PUBLIC_KEY,
                   matcherPublicKey: matcherKey,
                   amountAsset: WAVES_ID,
                   priceAsset: HYBRID_TOKEN_ID,
                   orderType: 'buy', // 'buy' or 'sell'
                   amount: 123,
                   price: 123,
                   timestamp: Date.now(),
                   expiration: Date.now() + 10000000000,
                   matcherFee: -30000
                 }, {
                   publicKey: PUBLIC_KEY,
                   privateKey: PRIVATE_KEY
                 }))
                )

  orderStream.subscribe(x => console.log('Status', x));
```

**Comment by xenohunter** [comment]
Hello, Marco! Sorry for the long delay before this answer, and thank you for your kind words!

It should be a server issue, certainly. Are you still experiencing that request error?

**Comment by 0xae** [comment]
@xenohunter  hello there, dont know about @marcoalkema  but i am experiencing the same issues too.
here's the code
```
let BITCOIN='Fk7x7tDcXJFFRLD21iTkj1cUVk5XNHFVoiXRy6sw7S84';
let RIPPLE='B7mqGR7mCgYdpzxBgW2sG4rZQZLAF2jcGMsxfTDPG9R5';

var order = {
    matcherPublicKey: '3tWuqg9syHTsdmNNmwUbguLUhnpyE5AS4rpkojgm6aw2',
    priceAsset: BITCOIN, 
    amountAsset: RIPPLE,
    amount: 12000,
    price: 1900,
    orderType: 'sell'
};

Waves.API.Matcher.v1.createOrder(order, bot)
.then((res) => {
    console.info(chalk.bgGreen("OPEN TRADE"));
    console.info("result: ", res);
}, (error) => {
    console.error(chalk.bgRed("An error ocurred: "));
    console.error(error);
});

```

but the server keep sending this error:
```
{ WavesRequestError: Server request to 'http://127.0.0.1:6862/matcher/orderbook' has failed:

FetchError: redirect location header missing at: http://127.0.0.1:6862/matcher/orderbook

    at new WavesRequestError (/home/ayrton/env/git/unlimitedPN/Unlimited.Exchange/exchange-web/node_modules/waves-api/dist/waves-api.min.js:1:251106)
    at handleError (/home/ayrton/env/git/unlimitedPN/Unlimited.Exchange/exchange-web/node_modules/waves-api/dist/waves-api.min.js:1:325772)
    at /home/ayrton/env/git/unlimitedPN/Unlimited.Exchange/exchange-web/node_modules/waves-api/dist/waves-api.min.js:1:326092
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'WavesRequestError',
  data: 
   { FetchError: redirect location header missing at: http://127.0.0.1:6862/matcher/orderbook
    at ClientRequest.<anonymous> (/home/ayrton/env/git/unlimitedPN/Unlimited.Exchange/exchange-web/node_modules/node-fetch/index.js:152:13)
    at ClientRequest.emit (events.js:159:13)
    at HTTPParser.parserOnIncomingClient (_http_client.js:550:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at Socket.socketOnData (_http_client.js:439:20)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:598:20)
     name: 'FetchError',
     message: 'redirect location header missing at: http://127.0.0.1:6862/matcher/orderbook',
     type: 'invalid-redirect' } }
```

thanks for your attention, any help is appreciated

**Comment by xenohunter** [comment]
Hi, @0xae! It seems to be an issue on the side of the matcher. If you still have it, please, try contacting the backend team here: https://github.com/wavesplatform/Waves.
