### ISSUE TITLE
Browserify support

### ISSUE THREAD

**Issue by siemarell** [wavesplatform/waves-api#64]
#### Library installed via npm doesn't support browserify
Example code in test.js:
```javascript
var WavesApi = require('@waves/waves-api')
```
Command to run:
```
browserify test.js 
```
Stacktrace:
```
Error: Cannot find module '../libs/base58' from '/home/sborzov/WebstormProjects/browserifyTest/node_modules/@waves/waves-api/dist'
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:158:21)
```
Workaround can be found here: https://github.com/browserify/browserify/issues/374
AFAIK library can be built using --standalone flag to support browserify out of the box

**Comment by xenohunter** [comment]
Hello! Thanks for reporting, but I don't see how that behavior could be an issue if all works with a flag.
