### ISSUE TITLE
Transfer transaction error

### ISSUE THREAD

**Issue by flute** [wavesplatform/waves-api#79]
I'm trying to make a WAVES coin transaction, and i just followed this step:

![image](https://user-images.githubusercontent.com/5842406/44147164-826639d8-a0c5-11e8-9d68-cb5a4b1dde9e.png)

While it shows error:

```bash
Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11
    at Object.oldBrowser (/Users/ludis/Mac/iqb/recwaves/node/node_modules/._@waves_waves-api@1.4.0@@waves/waves-api/dist/waves-api.min.js:1:547386)
    at nodeRandom (/Users/ludis/Mac/iqb/recwaves/node/node_modules/._@waves_waves-api@1.4.0@@waves/waves-api/dist/waves-api.min.js:1:65695)
    at secureRandom (/Users/ludis/Mac/iqb/recwaves/node/node_modules/._@waves_waves-api@1.4.0@@waves/waves-api/dist/waves-api.min.js:1:66689)
    at Object.randomUint8Array (/Users/ludis/Mac/iqb/recwaves/node/node_modules/._@waves_waves-api@1.4.0@@waves/waves-api/dist/waves-api.min.js:1:66920)
    at Object.buildTransactionSignature (/Users/ludis/Mac/iqb/recwaves/node/node_modules/._@waves_waves-api@1.4.0@@waves/waves-api/dist/waves-api.min.js:1:86992)
    at getBytes.then.dataBytes (/Users/ludis/Mac/iqb/recwaves/node/node_modules/._@waves_waves-api@1.4.0@@waves/waves-api/dist/waves-api.min.js:1:78050)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
```

It seems caused by same bug as #69

**Comment by xenohunter** [comment]
We fixed that bug. Starting with [version 1.5.0](https://github.com/wavesplatform/waves-api/releases/tag/1.5.0), everything will work fine.
